<div class="row-fluid" style="background:#e7e8ea;margin-bottom:10px">
<?php

$colors = array('magenta','green','cyan','grey','blue','magenta','green','cyan','grey','blue');

$model = new Blog_Model_Tree();
$model2 = new Menu_Model_TopItems();
$data = $model2->fetchAll('1','order_num ASC');

$i = 1;
foreach($data as $row){
    $treeData = $model->getRow($row->tree_id);
    $class = '';

    if(isset($this->currentCategories[$row->tree_id])){
        $class = 'class="active"';
    }

    $url = '';
    if($treeData != null){
        $url = $treeData->url_name;
    }
if(count($data)==$i){
    echo '<div class="navNew end"><a class="grey" href="/'.$url.'">'.$row->name.'</a></div>';
}else{
    echo '<div class="navNew"><a class="grey" href="/'.$url.'">'.$row->name.'</a></div>';
}
    $i++;
}
?>
</div>
