<div class="row-fluid">
      <h1><?php echo $this->tree->name;?></h1>

<div class="span6">

<?php


if(isset($this->ok)){
    echo '<script>alert("'.text('Formulár bol úspešne odoslaný. Ďakujeme').'")</script>';
}
if(isset($this->error)){
    echo '<script>alert("'.text('Formulár bol nesprávne vyplnený, skúste to ešte raz.').'")</script>';
}
?>
<?php echo $this->data->googlemap;?>
<br /><br />

<?php echo $this->data->text;?>

</div>
<div class="span5">





<form id="ContactForm" action="" method="post">
  <fieldset>
<h2><?php echo $this->data->form_name;?></h2>
<p><?php echo $this->data->form_text;?></p>

<label>Vaše meno (povinné)</label>
<input type="text" value="<?php echo $this->form->getElement('name')->getValue();?>" name="name" />
<label>Váš email (povinné)</label>
<input type="text"  value="<?php echo $this->form->getElement('email')->getValue();?>"  name="email" />
<label>Váš Telefón:</label>
<input type="text" value="<?php echo $this->form->getElement('phone')->getValue();?>"  name="phone" />
<label>Vaša správa:</label>
<textarea name="message" style="height:100px;width:260px"><?php echo $this->form->getElement('message')->getValue();?></textarea>
<br style="clear:both" />
<input type="submit" value="Odoslať" class="btn">
  <dt class="iamrobot"><?php echo text('Toto pole nechajte prosím prázdne');?>:</dt><dd  class="iamrobot"><input type="text" value="<?php echo $this->form->getElement('iamrobot')->getValue();?>"  name="iamrobot"  /><dd>
  <dt class="iamhuman"><?php echo text('Do tohto poľa napíšte "ano"');?>:</dt><dd  class="iamhuman"><input id="iamhuman" type="text" value="<?php echo $this->form->getElement('iamhuman')->getValue();?>"  name="iamhuman" /><dd>


  </fieldset>
</form>

</div>
</div>



  <script>
  $(".iamrobot").hide();
  $(".iamhuman").hide();
  $("#iamhuman").val("ano");
  </script>


