<!DOCTYPE html>
<html>
<head>

    <meta charset="utf-8">
    <title><?php echo Cms_T::_('cms_error'); ?></title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="author" content="GQsystems s.r.o. | Filip Gergely, Marek Hattas">
    <link REL="SHORTCUT ICON" HREF="/favicon.ico">

    <link href="/admin/bootstrap/css/bootstrap-yeti.min.css" rel="stylesheet" media="screen">
    <link href="/admin/stylesheets/style.css" media="screen" rel="stylesheet" />


</head>
<body>
    <div id="card_general" class="content container card_content">
        <div class="row">
            <div class="col-md-12" style="margin-top:50px">
                <?php echo $this->layout()->content; ?>
            </div>
        </div>
    </div>

</body>
</html>
